### ISSUE TITLE
use trained Transformer for decoding in another pipeline, has gpu memory error 

### ISSUE THREAD

**Issue by vincentliuk** [dmlc/gluon-nlp#352]
Hi,
I am using transformer(Attention is all you need) to train a model on aws p3.2xLarge, with args as:
args = {
  "n_samples": -1,
  "epochs": 40,
  "num_units": 512,
  "hidden_size": 2048,
  "dropout": 0.1,
  "epsilon": 0.1,
  "num_layers": 6,
  "num_heads": 8,
  "scaled": True,
  "batch_size": 2048,
  "beam_size": 20,
  "lp_alpha": 0.6,
  "lp_k": 5,
  "test_batch_size": 128,
  "num_buckets": 10,
  "bucket_scheme": "constant",
  "bucket_ratio": 0.0,
  "src_max_len": 500,
  "tgt_max_len": 500,
  "optimizer": "adam",
  "lr": 1.0,
  "warmup_steps": 4000,
  "num_accumulated": 1,
  "magnitude": 3.0,
  "average_checkpoint": True,
  "num_averages": 5,
  "average_start": 5,
  "full": True,
  "bleu": "tweaked",
  "log_interval": 100,
  "save_dir": "dummy",
  "gpus": "0"
}

After training, I used this trained model only for decoding (inference) inserted into another pipeline on the same aws p3.2xLarge. However, during our pipeline code running (after run a while), it reports the error as :
/home/travis/build/dmlc/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:62: Check failed: e == cudaSuccess CUDA: an illegal memory access was encountered

I am sure it is not only the batch size issue, since it can run a while. It seemed there are some cache memory issue accumulated in gpu. If I reduce the model size or batch size for pipeline, it will elongate the running but failed later as well. 

Anyone has thoughts about this?
Thank you so much,

**Comment by szha** [comment]
w/ p3 instances (V100 GPU), the random states from dropout takes quite some memory which is not managed by mxnet. This means the default value of MXNET_GPU_MEM_POOL_RESERVE environment variable, which is 5, might not be enough. To mitigate, set it to 7 or something larger.

**Comment by vincentliuk** [comment]
I tried export MXNET_GPU_MEM_POOL_RESERV=10 before jupyter notebook running. The running is frozen, though no memory error reported. It showed volatile GPU-util was 100%, and wait for while, no changing.

**Comment by leezu** [comment]
Can you try if this issue persists if you run your code as a "normal" python script (ie. not jupyter notebook)? Sometimes jupyter notebook seems to cause issues.

**Comment by szha** [comment]
@vincentliuk turns out there was a bug in transformer's construction in the train_transformer script. It was fixed in #414.
